CREATE DATABASE IF NOT EXISTS kironoa;
USE kironoa;

CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    passcode_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    count INT DEFAULT 0
);

INSERT INTO visits (id, count) VALUES (1, 0)
ON DUPLICATE KEY UPDATE count = count;
